# Create an access token in the dashboard settings page
@accessToken = vault_58b9cbcdfa58dd203847cf21e47b824857db61da302fafc365
@host = {{$dotenv WEBSITE_HOST}}

###

GET {{host}}/api/contacts
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/contacts/+17146236604
Authorization: Bearer {{accessToken}}

###
