# Create an access token in the dashboard settings page
@accessToken = ctx_your_access_token_here
@host = {{$dotenv WEBSITE_HOST}}

###

GET {{host}}/api/contacts
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/contacts/+17146236604
Authorization: Bearer {{accessToken}}

###
