# Create an access token in the dashboard settings page
@accessToken = ctx_your_access_token_here
@host = {{$dotenv WEBSITE_HOST}}

###

GET {{host}}/api/imessage/chats
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/imessage/chats/+18573319216/messages
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/imessage/latest?within_min=60
Authorization: Bearer {{accessToken}}
