# Create an access token in the dashboard settings page
@accessToken = {{$dotenv EXAMPLE_ACCESS_TOKEN}}
@host = {{$dotenv WEBSITE_HOST}}

###

GET {{host}}/api/whatsapp/chats
Authorization: Bearer {{accessToken}}
































###

GET {{host}}/api/whatsapp/chats/5521985351968-1427149878@g.us/messages
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/whatsapp/latest?within_min=60
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/whatsapp/chats/search?senderPhoneNumberIndex=f6b2583f59d23e929b522be19dd6874352fe19959bbfdb8b76387e72bf7b5f70
Authorization: Bearer {{accessToken}}

####