# Create an access token in the dashboard settings page
@accessToken = vault_7ebbf837e9676f3e6d9256f2e567ac3577c01d6af8abf20f49
# @host = {{$dotenv WEBSITE_HOST}}
@host = http://localhost:3030

###

GET {{host}}/api/whatsapp/chats
Authorization: Bearer {{accessToken}}
































###

GET {{host}}/api/whatsapp/chats/5521985351968-1427149878@g.us/messages
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/whatsapp/latest?within_min=60
Authorization: Bearer {{accessToken}}

###

GET {{host}}/api/whatsapp/chats/search?senderPhoneNumberIndex=f6b2583f59d23e929b522be19dd6874352fe19959bbfdb8b76387e72bf7b5f70
Authorization: Bearer {{accessToken}}

####